# Some practices done in this file is not suitable for production environmnents or can cause bugs
# The main reason to change the standard way is to make container node_modules available for host
# this way vscode intellisense works correctly
FROM node:12-alpine

EXPOSE 3000

WORKDIR /usr/app

COPY package.json yarn.lock ./

RUN yarn add react-scripts@3.4.1 -g

COPY . .

CMD yarn && yarn start
